### ISSUE TITLE
Empty config.json after intialization

### ISSUE THREAD

**Issue by zhaobenny** [HelloGrasscutter/HelloGrasscutter#4]
Using the docker-compose.yml provided, the created config.json is empty after intialization.
```
HelloGrasscutter | /entrypoint.sh: Start initialization.
HelloGrasscutter | cp: can't stat '/keys': No such file or directory
HelloGrasscutter | cp: can't stat '/data': No such file or directory
HelloGrasscutter | /entrypoint.sh: Downloading resources...
HelloGrasscutter | /entrypoint.sh: Copying resources...
HelloGrasscutter | /entrypoint.sh: Generating configuration...
HelloGrasscutter | cat: can't open 'config.json': No such file or directory
HelloGrasscutter | /entrypoint.sh: Initialization complete!
HelloGrasscutter | Exception in thread "main" java.lang.ExceptionInInitializerError
HelloGrasscutter | Caused by: java.lang.NullPointerException: Cannot read field "version" because "emu.grasscutter.Grasscutter.config" is null
HelloGrasscutter |      at emu.grasscutter.config.ConfigContainer.updateConfig(ConfigContainer.java:36)
HelloGrasscutter |      at emu.grasscutter.Grasscutter.<clinit>(Grasscutter.java:85)
```

**Comment by Becods** [comment]
Too many upstream changes to initialise properly and I don't have enough time to maintain the project at the moment, so I suggest you use [akbaryahya/DockerGC](https://github.com/akbaryahya/DockerGC)
